# Generated by Django 3.1.9 on 2021-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TConstant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('param_key', models.CharField(max_length=32)),
                ('param_name', models.CharField(max_length=64)),
                ('param_value', models.CharField(max_length=256)),
                ('remark', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '配置常量',
                'verbose_name_plural': '配置常量',
                'db_table': 't_constant',
                'managed': False,
            },
        ),
    ]
