# Generated by Django 3.1.9 on 2021-06-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210622_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='constant',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
